# Generated by Django 5.1.3 on 2024-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student', max_length=10),
        ),
    ]
