# Generated by Django 5.1.3 on 2024-12-30 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_facultyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facultyprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
