# Generated by Django 5.2 on 2025-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='rag_chatbot/data/faculty/resumes/'),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='rag_chatbot/data/faculty/lectures/'),
        ),
    ]
